# docker-compose.yml

version: '3'

services:
  web:
    container_name: docker-compose-mysql-web
    build: ./docker/web
    ports:
      - '80:80'
    volumes:
      - ../html:/var/www/html
    hostname: localhost
    networks:
      - br0
  mysql:
    container_name: docker-compose-mysql-mysql
    build: ./docker/db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT}:3306'
    hostname: localhost
    restart: always
    environment:
      # ユーザーアカウントとDBを設定
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_HOST: '${DB_HOST}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      TZ: '${TZ}'
    networks:
      - br0
  phpmyadmin:
    container_name: docker-compose-mysql-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '${FORWARD_PMA_PORT}:80'
    restart: always
    environment:
      # mysqlにコンテナに接続
      PMA_HOST: '${DB_HOST}'
    networks:
      - br0

networks:
  br0:
    driver: bridge